# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Six Honest Serving-Men
tagline:          Medicine, Writing, and Other Pursuits
description:      Documenting the journey of a medical student
url:              http://milkcircle.github.io
baseurl:          /

author:
  name:           'Aaron Cheng'
  url:            http://milkcircle.github.io
  
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/milkcircle/milkcircle.github.io
