# Site settings
title: Aaron Cheng
email: aaron_cheng@hms.harvard.edu
description: "Aaron Cheng"
baseurl: ""
url: ""
# twitter_username: 
# github_username: milkcircle

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
paginate: 10
paginate_path: "/posts/:num/"