##The website title
name: Six Honest Serving-Men
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: http://milkcircle.github.io
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: Put website description for your home page. (about 50 words or more)
##Some frequently used keywords on your website
keywords: medicine, writing, code, math, photography

##define this for disqus comment support
disqus: sixhonestservingmen

##set this to enable google analytics
ga_id: UA-64904363-1
ga_domain: http://milkcircle.github.io

##Some commonly used links
links:
  #facebook: narfnarfnarfnarf
  #twitter: username
  email: Aaron_Cheng@hms.harvard.edu
  #github: 

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: profpic.jpg
##comment this if you want full width posts with no sidebar
#sidebar: on
