title: Six Honest Serving-Men
description: A medical student's personal website

url: http://milkcircle.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 #- title: Contact
 #  url: /contact
 - title: Archive
   url: /archive
 - title: Photography
   url: /photography

social:
   #github: brianmaierjr
   #twitter: brianmaierjr
   #facebook: brianmaierjr
   email: aaron_cheng@hms.harvard.edu

google_analytics: "UA-64904363-1"
