# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            New Blood
tagline:          Medicine, coding, and other pursuits
description:      Documenting the adventure of a premedical student
url:              http://milkcircle.github.io
baseurl:          /

author:
  name:           'Aaron Cheng'
  url:            http://milkcircle.github.io
  
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/milkcircle/milkcircle.github.io
